---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservicedeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      name: userservice
  template:
    metadata:
      labels:
        name: userservice
    spec:
      containers:
      - name: application
        image: leo600/user-service:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000